In [2]:
import numpy as np

import pandas as pd

In [ ]:
""" Pandas """

In [2]:
[1, 3, 5, 7, 8, 9]

[1, 3, 5, 7, 8, 9]

In [3]:
s = pd.Series([1, 3, 5, 7, 8, 9])

s

0    1
1    3
2    5
3    7
4    8
5    9
dtype: int64

In [4]:
# Random data generation from "standard normal distribution"
np.random.randn(6, 4)

array([[-0.01110104,  0.15558092,  0.60425784, -0.53760742],
       [-0.70112467, -2.60966983, -1.06011007,  0.75015461],
       [-0.09276336, -0.28419374,  0.23800565, -1.09659463],
       [-0.70944792, -0.2954511 , -0.39847293, -0.30754529],
       [-1.71099142,  0.97460539, -0.11665121,  0.88074214],
       [-0.84409147,  0.69649141,  1.7943037 ,  1.50260045]])

In [5]:
# Create dataframe from numpy matrix
df = pd.DataFrame(np.random.randn(6, 4), columns=['A', 'B', 'C', 'D'])

df

A         B         C         D
0  0.261644 -1.068515  0.592608  0.388943
1  0.004562 -0.067607  1.276591 -1.631235
2 -1.173389  0.766999  1.401126 -0.709889
3  1.749407  1.172196  0.420880 -0.720130
4 -0.950177  0.356857 -1.038518 -1.178869
5  0.585548 -0.095760  0.237023  2.424021

In [22]:
# Create dataframe from dictionary
data_dictionary = {'Product': ['A', 'B', 'C', 'A', 'D'],
                   'Grade': [1, 2, 1, 1, 3],
                   'Price ($)': [4, 2.5, 3.5, 3, 0.5]}

df_dictionary = pd.DataFrame(data_dictionary)

df_dictionary

Product  Grade  Price ($)
0       A      1        4.0
1       B      2        2.5
2       C      1        3.5
3       A      1        3.0
4       D      3        0.5

In [16]:
# Viewing data
print('df.head()')
print(df.head())

print('')

print('df.head(3)')
print(df.head(3))

df.head()
          A         B         C         D
0  0.261644 -1.068515  0.592608  0.388943
1  0.004562 -0.067607  1.276591 -1.631235
2 -1.173389  0.766999  1.401126 -0.709889
3  1.749407  1.172196  0.420880 -0.720130
4 -0.950177  0.356857 -1.038518 -1.178869

df.head(3)
          A         B         C         D
0  0.261644 -1.068515  0.592608  0.388943
1  0.004562 -0.067607  1.276591 -1.631235
2 -1.173389  0.766999  1.401126 -0.709889


In [15]:
print('df.tail()')
print(df.tail())

print('')

print('df.tail(3)')
print(df.tail(3))

df.tail()
          A         B         C         D
1  0.004562 -0.067607  1.276591 -1.631235
2 -1.173389  0.766999  1.401126 -0.709889
3  1.749407  1.172196  0.420880 -0.720130
4 -0.950177  0.356857 -1.038518 -1.178869
5  0.585548 -0.095760  0.237023  2.424021

df.tail(3)
          A         B         C         D
3  1.749407  1.172196  0.420880 -0.720130
4 -0.950177  0.356857 -1.038518 -1.178869
5  0.585548 -0.095760  0.237023  2.424021


In [21]:
# access to columns names
df.columns

Index(['A', 'B', 'C', 'D'], dtype='object')

In [20]:
# dataframe to numpy array
print('df.to_numpy()')
print(df.to_numpy())

df.to_numpy()


NameError: name 'df' is not defined

In [30]:
# sorting by values
df.sort_values(by='B', ascending=False)

A         B         C         D
3  1.749407  1.172196  0.420880 -0.720130
2 -1.173389  0.766999  1.401126 -0.709889
4 -0.950177  0.356857 -1.038518 -1.178869
1  0.004562 -0.067607  1.276591 -1.631235
5  0.585548 -0.095760  0.237023  2.424021
0  0.261644 -1.068515  0.592608  0.388943

In [ ]:
# related to nan
df.isna()
df.notna()
df.dropna()
df.fillna()

In [24]:
df2 = pd.DataFrame(np.random.choice([1, 2, 3, 4, np.nan], size=[20, 5]))
df2

0    1    2    3    4
0   4.0  4.0  1.0  4.0  3.0
1   1.0  NaN  4.0  2.0  2.0
2   3.0  NaN  NaN  NaN  2.0
3   2.0  1.0  1.0  4.0  1.0
4   NaN  2.0  3.0  NaN  1.0
5   NaN  4.0  4.0  4.0  3.0
6   1.0  4.0  1.0  3.0  NaN
7   1.0  4.0  1.0  4.0  3.0
8   3.0  1.0  1.0  1.0  NaN
9   NaN  1.0  1.0  4.0  4.0
10  NaN  1.0  2.0  NaN  NaN
11  4.0  2.0  4.0  1.0  NaN
12  3.0  2.0  3.0  2.0  1.0
13  1.0  2.0  NaN  3.0  NaN
14  4.0  1.0  3.0  1.0  2.0
15  NaN  4.0  4.0  3.0  3.0
16  2.0  3.0  4.0  1.0  4.0
17  4.0  1.0  2.0  NaN  4.0
18  3.0  1.0  2.0  3.0  1.0
19  3.0  3.0  1.0  1.0  2.0

In [27]:
df2.drop(columns=[0, 4])

1    2    3
0   4.0  1.0  4.0
1   NaN  4.0  2.0
2   NaN  NaN  NaN
3   1.0  1.0  4.0
4   2.0  3.0  NaN
5   4.0  4.0  4.0
6   4.0  1.0  3.0
7   4.0  1.0  4.0
8   1.0  1.0  1.0
9   1.0  1.0  4.0
10  1.0  2.0  NaN
11  2.0  4.0  1.0
12  2.0  3.0  2.0
13  2.0  NaN  3.0
14  1.0  3.0  1.0
15  4.0  4.0  3.0
16  3.0  4.0  1.0
17  1.0  2.0  NaN
18  1.0  2.0  3.0
19  3.0  1.0  1.0

In [ ]:
df2.drop(index=[2, 10])

In [ ]:
df.drop_duplicates()

In [ ]:
""" Numpy """

In [5]:
arr = np.arange(100)
arr_2d = arr.reshape(-1, 5)

arr_2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64],
       [65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74],
       [75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84],
       [85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94],
       [95, 96, 97, 98, 99]])

In [6]:
arr_2d = arr.reshape(-1, 3)

ValueError: cannot reshape array of size 100 into shape (3)

In [ ]:
# transform into 1-dimensional array
arr_2d.ravel()
arr_2d.flatten()

In [ ]:
# transpose
arr_2d.T

In [9]:
# np.where, np.argwhere
arr2 = np.random.choice(5, size=[20, 5])
arr2

array([[3, 0, 1, 4, 4],
       [0, 1, 3, 1, 0],
       [2, 0, 3, 3, 4],
       [4, 1, 2, 2, 4],
       [2, 2, 3, 2, 4],
       [3, 0, 4, 1, 4],
       [3, 3, 0, 4, 1],
       [1, 1, 4, 0, 0],
       [3, 1, 3, 4, 1],
       [1, 0, 3, 3, 1],
       [1, 2, 1, 1, 4],
       [2, 3, 4, 3, 1],
       [2, 0, 1, 3, 2],
       [0, 1, 1, 2, 4],
       [3, 3, 1, 4, 3],
       [4, 2, 4, 1, 0],
       [0, 4, 4, 0, 3],
       [1, 1, 0, 2, 0],
       [4, 0, 2, 0, 4],
       [2, 0, 2, 3, 4]])

In [10]:
arr2 == 2

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [ True, False, False, False, False],
       [False, False,  True,  True, False],
       [ True,  True, False,  True, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False,  True, False, False, False],
       [ True, False, False, False, False],
       [ True, False, False, False,  True],
       [False, False, False,  True, False],
       [False, False, False, False, False],
       [False,  True, False, False, False],
       [False, False, False, False, False],
       [False, False, False,  True, False],
       [False, False,  True, False, False],
       [ True, False,  True, False, False]])

In [11]:
np.where(arr2 == 2)

(array([ 2,  3,  3,  4,  4,  4, 10, 11, 12, 12, 13, 15, 17, 18, 19, 19],
       dtype=int64),
 array([0, 2, 3, 0, 1, 3, 1, 0, 0, 4, 3, 1, 3, 2, 0, 2], dtype=int64))

In [14]:
type(np.where(arr2 == 2))

tuple

In [15]:
np.where(arr2 == 2)[0]

array([ 2,  3,  3,  4,  4,  4, 10, 11, 12, 12, 13, 15, 17, 18, 19, 19],
      dtype=int64)

In [16]:
np.where(arr2 == 2)[1]

array([0, 2, 3, 0, 1, 3, 1, 0, 0, 4, 3, 1, 3, 2, 0, 2], dtype=int64)

In [31]:
np.argwhere(arr2 == 2)

array([[ 2,  0],
       [ 3,  2],
       [ 3,  3],
       [ 4,  0],
       [ 4,  1],
       [ 4,  3],
       [10,  1],
       [11,  0],
       [12,  0],
       [12,  4],
       [13,  3],
       [15,  1],
       [17,  3],
       [18,  2],
       [19,  0],
       [19,  2]], dtype=int64)

In [33]:
np.isin(arr2, [1, 2])

array([[False, False,  True, False, False],
       [False,  True, False,  True, False],
       [ True, False, False, False, False],
       [False,  True,  True,  True, False],
       [ True,  True, False,  True, False],
       [False, False, False,  True, False],
       [False, False, False, False,  True],
       [ True,  True, False, False, False],
       [False,  True, False, False,  True],
       [ True, False, False, False,  True],
       [ True,  True,  True,  True, False],
       [ True, False, False, False,  True],
       [ True, False,  True, False,  True],
       [False,  True,  True,  True, False],
       [False, False,  True, False, False],
       [False,  True, False,  True, False],
       [False, False, False, False, False],
       [ True,  True, False,  True, False],
       [False, False,  True, False, False],
       [ True, False,  True, False, False]])

In [32]:
np.in1d(arr2, [1, 2])

array([False, False,  True, False, False, False,  True, False,  True,
       False,  True, False, False, False, False, False,  True,  True,
        True, False,  True,  True, False,  True, False, False, False,
       False,  True, False, False, False, False, False,  True,  True,
        True, False, False, False, False,  True, False, False,  True,
        True, False, False, False,  True,  True,  True,  True,  True,
       False,  True, False, False, False,  True,  True, False,  True,
       False,  True, False,  True,  True,  True, False, False, False,
        True, False, False, False,  True, False,  True, False, False,
       False, False, False, False,  True,  True, False,  True, False,
       False, False,  True, False, False,  True, False,  True, False,
       False])

In [ ]:
# set operations
np.setdiff1d
np.setxor1d
np.union1d
np.intersect1d

In [36]:
# sorting
np.sort(arr2)

array([[0, 1, 3, 4, 4],
       [0, 0, 1, 1, 3],
       [0, 2, 3, 3, 4],
       [1, 2, 2, 4, 4],
       [2, 2, 2, 3, 4],
       [0, 1, 3, 4, 4],
       [0, 1, 3, 3, 4],
       [0, 0, 1, 1, 4],
       [1, 1, 3, 3, 4],
       [0, 1, 1, 3, 3],
       [1, 1, 1, 2, 4],
       [1, 2, 3, 3, 4],
       [0, 1, 2, 2, 3],
       [0, 1, 1, 2, 4],
       [1, 3, 3, 3, 4],
       [0, 1, 2, 4, 4],
       [0, 0, 3, 4, 4],
       [0, 0, 1, 1, 2],
       [0, 0, 2, 4, 4],
       [0, 2, 2, 3, 4]])

In [ ]:
np.argsort(arr2)

In [ ]:
np.argmax
np.argmin

In [ ]:
np.max
np.min
np.nanmax
np.nanmin

np.mean
np.nanmean
np.std
np.nanstd
np.var
np.nanvar

In [38]:
np.random.rand
np.random.randn
np.random.randint
np.random.choice

array([0.96930323, 0.92011963, 0.31757244, 0.21977078, 0.62158153,
       0.26752429, 0.33025926, 0.59791701, 0.61044921, 0.66768826,
       0.71624226, 0.26357063, 0.80176772, 0.6799356 , 0.33610096,
       0.31441685, 0.02626316, 0.04600306, 0.07218507, 0.4617409 ,
       0.646876  , 0.89526762, 0.26747599, 0.97500452, 0.72228905,
       0.02075053, 0.94807893, 0.52993395, 0.5054757 , 0.18467313,
       0.61134579, 0.60353787, 0.93221196, 0.2690681 , 0.5544001 ,
       0.02200685, 0.55489447, 0.56035428, 0.27019734, 0.48328573,
       0.69811195, 0.76392477, 0.25524967, 0.94366196, 0.25507064,
       0.9583366 , 0.16199523, 0.16583148, 0.04417132, 0.45927685,
       0.38887102, 0.04893331, 0.05798639, 0.03666532, 0.73768248,
       0.25267954, 0.09217124, 0.69090139, 0.08365703, 0.12458055,
       0.09975049, 0.19154108, 0.71231331, 0.11408717, 0.82425333,
       0.73386527, 0.16107186, 0.64786522, 0.36379511, 0.57873232,
       0.6183269 , 0.22356044, 0.03201742, 0.79919289, 0.89365

In [48]:
a = [1, 2, 3]
b = [2, 3, 4]

array([[1, 2, 3],
       [2, 3, 4]])

In [ ]:
np.c_
np.r_

np.vstack
np.hstack

In [ ]:
np.split(arr, 10)
np.array_split

In [46]:
arr_bool = np.random.choice([True, False], size=[20, 5], p=[0.9, 0.1])
arr_bool

array([[ True, False,  True,  True,  True],
       [ True,  True, False,  True, False],
       [ True,  True,  True,  True,  True],
       [False,  True,  True,  True,  True],
       [ True,  True,  True,  True, False],
       [False,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True, False,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True, False,  True,  True],
       [ True,  True,  True,  True,  True],
       [False,  True, False,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True, False],
       [ True,  True,  True,  True, False],
       [ True,  True, False,  True,  True],
       [ True,  True,  True,  True,  True]])

In [ ]:
np.any
np.all

In [ ]:
np.unique

In [ ]:
np.ones
np.zeros