In [1]:
#. Numpy, Pandas 라이브러리 import
import numpy as np
import pandas as pd

In [2]:
dataset = pd.read_csv('pima-indians-diabetes_edited.csv')
print(dataset.head(20))

     0      1     2     3      4     5      6   7  8
0    6  148.0  72.0  35.0    NaN  33.6  0.627  50  1
1    1   85.0  66.0  29.0    NaN  26.6  0.351  31  0
2    8  183.0  64.0   NaN    NaN  23.3  0.672  32  1
3    1   89.0  66.0  23.0   94.0  28.1  0.167  21  0
4    0  137.0  40.0  35.0  168.0  43.1  2.288  33  1
5    5  116.0  74.0   NaN    NaN  25.6  0.201  30  0
6    3   78.0  50.0  32.0   88.0  31.0  0.248  26  1
7   10  115.0   NaN   NaN    NaN  35.3  0.134  29  0
8    2  197.0  70.0  45.0  543.0  30.5  0.158  53  1
9    8  125.0  96.0   NaN    NaN   NaN  0.232  54  1
10   4  110.0  92.0   NaN    NaN  37.6  0.191  30  0
11  10  168.0  74.0   NaN    NaN  38.0  0.537  34  1
12  10  139.0  80.0   NaN    NaN  27.1  1.441  57  0
13   1  189.0  60.0  23.0  846.0  30.1  0.398  59  1
14   5  166.0  72.0  19.0  175.0  25.8  0.587  51  1
15   7  100.0   NaN   NaN    NaN  30.0  0.484  32  1
16   0  118.0  84.0  47.0  230.0  45.8  0.551  31  1
17   7  107.0  74.0   NaN    NaN  29.6  0.254 

In [3]:
# 단계 1. 학습 데이터/테스트 데이터 분리
# 결측이 아닌 위치 추출
notna_bool = dataset.notna()
notna_bool_arr = notna_bool.to_numpy()

non_missing_idx = np.argwhere(dataset.notna().to_numpy())
print(non_missing_idx)

[[  0   0]
 [  0   1]
 [  0   2]
 ...
 [767   6]
 [767   7]
 [767   8]]


In [4]:
print(non_missing_idx.shape)

(6262, 2)


In [5]:
# 결측치 아닌 위치 array를 분할
from sklearn.model_selection import train_test_split
idx = np.arange(non_missing_idx.shape[0])
# option 1. absolute size of test set
num_test = 1000
train_idx, test_idx = train_test_split(idx, test_size=num_test)
# option 2. ratio of test set
ratio_test = 0.2
train_idx, test_idx = train_test_split(idx, test_size=ratio_test)

In [6]:
# dataset 복사 후 test_set 제거
dataset_incomplete = np.array(dataset.copy())
dataset_incomplete

array([[  6.   , 148.   ,  72.   , ...,   0.627,  50.   ,   1.   ],
       [  1.   ,  85.   ,  66.   , ...,   0.351,  31.   ,   0.   ],
       [  8.   , 183.   ,  64.   , ...,   0.672,  32.   ,   1.   ],
       ...,
       [  5.   , 121.   ,  72.   , ...,   0.245,  30.   ,   0.   ],
       [  1.   , 126.   ,  60.   , ...,   0.349,  47.   ,   1.   ],
       [  1.   ,  93.   ,  70.   , ...,   0.315,  23.   ,   0.   ]])

In [7]:
dataset_incomplete[non_missing_idx[test_idx, 0], non_missing_idx[test_idx, 1]] = np.nan

print('Original')
print(dataset.head(20))

print('')

print('Masked')
print(pd.DataFrame(dataset_incomplete).head(20))

Original
     0      1     2     3      4     5      6   7  8
0    6  148.0  72.0  35.0    NaN  33.6  0.627  50  1
1    1   85.0  66.0  29.0    NaN  26.6  0.351  31  0
2    8  183.0  64.0   NaN    NaN  23.3  0.672  32  1
3    1   89.0  66.0  23.0   94.0  28.1  0.167  21  0
4    0  137.0  40.0  35.0  168.0  43.1  2.288  33  1
5    5  116.0  74.0   NaN    NaN  25.6  0.201  30  0
6    3   78.0  50.0  32.0   88.0  31.0  0.248  26  1
7   10  115.0   NaN   NaN    NaN  35.3  0.134  29  0
8    2  197.0  70.0  45.0  543.0  30.5  0.158  53  1
9    8  125.0  96.0   NaN    NaN   NaN  0.232  54  1
10   4  110.0  92.0   NaN    NaN  37.6  0.191  30  0
11  10  168.0  74.0   NaN    NaN  38.0  0.537  34  1
12  10  139.0  80.0   NaN    NaN  27.1  1.441  57  0
13   1  189.0  60.0  23.0  846.0  30.1  0.398  59  1
14   5  166.0  72.0  19.0  175.0  25.8  0.587  51  1
15   7  100.0   NaN   NaN    NaN  30.0  0.484  32  1
16   0  118.0  84.0  47.0  230.0  45.8  0.551  31  1
17   7  107.0  74.0   NaN    NaN  29.

In [8]:
# 단계 2. 결측값 대입
from sklearn.impute import SimpleImputer
from sklearn.metrics import mean_squared_error
imputer_median = SimpleImputer(missing_values=np.nan, strategy ='median')
imputer_median.fit(dataset_incomplete)
dataset_filled_median = imputer_median.transform(dataset_incomplete)

In [9]:
dataset_filled_median

array([[  6.    , 148.    ,  72.    , ...,   0.627 ,  50.    ,   1.    ],
       [  3.    ,  85.    ,  72.    , ...,   0.351 ,  31.    ,   0.    ],
       [  3.    , 116.    ,  64.    , ...,   0.672 ,  29.    ,   1.    ],
       ...,
       [  3.    , 121.    ,  72.    , ...,   0.3645,  29.    ,   0.    ],
       [  1.    , 126.    ,  60.    , ...,   0.349 ,  29.    ,   1.    ],
       [  3.    ,  93.    ,  70.    , ...,   0.315 ,  23.    ,   0.    ]])

In [10]:
missing_true = np.array(dataset)[non_missing_idx[test_idx, 0], non_missing_idx[test_idx, 1]]
missing_pred_median = dataset_filled_median[non_missing_idx[test_idx, 0], non_missing_idx[test_idx, 1]]
mse_median = mean_squared_error(missing_true, missing_pred_median)
print(f'MSE-Median : {mse_median}')

MSE-Median : 1079.4539767968874


In [11]:
from fancyimpute import KNN, BiScaler, SoftImpute

c:\users\taekho\appdata\local\programs\python\python37\lib\site-packages\sklearn\externals\six.py:31: FutureWarning: The module is deprecated in version 0.21 and will be removed in version 0.23 since we've dropped support for Python 2.7. Please rely on the official version of six (https://pypi.org/project/six/).
  "(https://pypi.org/project/six/).", FutureWarning)
Using TensorFlow backend.


In [13]:
imputer_knn = 
dataset_filled_knn = 

Imputing row 1/768 with 1 missing, elapsed time: 0.119
Imputing row 101/768 with 3 missing, elapsed time: 0.124
Imputing row 201/768 with 1 missing, elapsed time: 0.128
Imputing row 301/768 with 4 missing, elapsed time: 0.131
Imputing row 401/768 with 4 missing, elapsed time: 0.135
Imputing row 501/768 with 1 missing, elapsed time: 0.139
Imputing row 601/768 with 2 missing, elapsed time: 0.143
Imputing row 701/768 with 0 missing, elapsed time: 0.148


In [14]:
missing_pred_knn = 
mse_knn = 
print("MSE-KNN : %f" % mse_knn)

MSE-KNN : 973.978009


In [19]:
biscaler = BiScaler()
biscaler.fit(dataset_incomplete)

dataset_incomplete_normalized = biscaler.transform(dataset_incomplete)

imputer_knn2 = 

dataset_filled_knn_norm = 
dataset_filled_knn2 = 

[BiScaler] Initial log residual value = 14.414355
[BiScaler] Iter 1: log residual = 4.134976, log improvement ratio=10.279379
[BiScaler] Iter 2: log residual = 3.529690, log improvement ratio=0.605286
[BiScaler] Iter 3: log residual = 3.001376, log improvement ratio=0.528314
[BiScaler] Iter 4: log residual = 2.524359, log improvement ratio=0.477018
[BiScaler] Iter 5: log residual = 2.008003, log improvement ratio=0.516356
[BiScaler] Iter 6: log residual = 1.428590, log improvement ratio=0.579413
[BiScaler] Iter 7: log residual = 0.790975, log improvement ratio=0.637615
[BiScaler] Iter 8: log residual = 0.108088, log improvement ratio=0.682887
[BiScaler] Iter 9: log residual = -0.606792, log improvement ratio=0.714880
[BiScaler] Iter 10: log residual = -1.342784, log improvement ratio=0.735992
[BiScaler] Iter 11: log residual = -2.092024, log improvement ratio=0.749240
[BiScaler] Iter 12: log residual = -2.849278, log improvement ratio=0.757254
[BiScaler] Iter 13: log residual = -3.6112

In [20]:
missing_pred_knn2 = 
mse_knn2 = 
print("MSE-KNN with Biscaler : %f" % mse_knn2)

MSE-KNN with Biscaler : 877.124098


In [21]:
imputer_soft = 

dataset_filled_soft = 

[SoftImpute] Max Singular Value of X_init = 4396.005017
[SoftImpute] Iter 1: observed MAE=2.130207 rank=7
[SoftImpute] Iter 2: observed MAE=2.145921 rank=6
[SoftImpute] Iter 3: observed MAE=2.153385 rank=6
[SoftImpute] Iter 4: observed MAE=2.161168 rank=6
[SoftImpute] Iter 5: observed MAE=2.169647 rank=6
[SoftImpute] Iter 6: observed MAE=2.177820 rank=6
[SoftImpute] Iter 7: observed MAE=2.185330 rank=6
[SoftImpute] Iter 8: observed MAE=2.191675 rank=6
[SoftImpute] Iter 9: observed MAE=2.197058 rank=6
[SoftImpute] Iter 10: observed MAE=2.200577 rank=6
[SoftImpute] Iter 11: observed MAE=2.203513 rank=6
[SoftImpute] Iter 12: observed MAE=2.205988 rank=6
[SoftImpute] Iter 13: observed MAE=2.207653 rank=6
[SoftImpute] Iter 14: observed MAE=2.208742 rank=6
[SoftImpute] Iter 15: observed MAE=2.209473 rank=6
[SoftImpute] Iter 16: observed MAE=2.210065 rank=6
[SoftImpute] Iter 17: observed MAE=2.210577 rank=6
[SoftImpute] Iter 18: observed MAE=2.211065 rank=6
[SoftImpute] Iter 19: observed MAE=

In [22]:
missing_pred_soft = 
mse_soft = 
print("MSE-Soft : %f" % mse_soft)

MSE-Soft : 1581.233291


In [23]:
imputer_soft2 = 

dataset_filled_soft_norm = 
dataset_filled_soft2 = biscaler.inverse_transform(dataset_filled_soft_norm)

[SoftImpute] Max Singular Value of X_init = 38.408750
[SoftImpute] Iter 1: observed MAE=0.024666 rank=8
[SoftImpute] Iter 2: observed MAE=0.024673 rank=8
[SoftImpute] Iter 3: observed MAE=0.024705 rank=8
[SoftImpute] Iter 4: observed MAE=0.024746 rank=8
[SoftImpute] Iter 5: observed MAE=0.024786 rank=8
[SoftImpute] Iter 6: observed MAE=0.024822 rank=8
[SoftImpute] Iter 7: observed MAE=0.024854 rank=8
[SoftImpute] Iter 8: observed MAE=0.024884 rank=8
[SoftImpute] Iter 9: observed MAE=0.024910 rank=8
[SoftImpute] Iter 10: observed MAE=0.024934 rank=8
[SoftImpute] Iter 11: observed MAE=0.024956 rank=8
[SoftImpute] Iter 12: observed MAE=0.024976 rank=8
[SoftImpute] Iter 13: observed MAE=0.024995 rank=8
[SoftImpute] Iter 14: observed MAE=0.025013 rank=8
[SoftImpute] Iter 15: observed MAE=0.025030 rank=8
[SoftImpute] Iter 16: observed MAE=0.025045 rank=8
[SoftImpute] Iter 17: observed MAE=0.025060 rank=8
[SoftImpute] Iter 18: observed MAE=0.025074 rank=8
[SoftImpute] Iter 19: observed MAE=0.

In [24]:
missing_pred_soft2 = 
mse_soft2 = 
print("MSE-Soft with Biscaler : %f" % mse_soft2)

MSE-Soft with Biscaler : 855.070915
