In [1]:
# 라이브러리 import
import numpy as np
import pandas as pd
import statsmodels.api as sm

In [2]:
# csv 데이터 파일 불러오기
data = pd.read_csv('검진데이터.csv')
data_np = data.to_numpy()

In [3]:
# 독립변수와 종속변수 분리
X= data_np[:,:-1]
y = data_np[:,-1]

In [4]:
X

array([[ 58. ,   1. ,   1. ,   2. , 108. ,  75. , 107. ],
       [ 38. ,   1. ,   2. ,   1. , 114. ,  73. , 155.7],
       [ 21. ,   1. ,   2. ,   1. , 167. , 125. ,  98. ],
       [ 38. ,   1. ,   2. ,   2. , 112. ,  64. , 125.4],
       [ 62. ,   1. ,   2. ,   1. , 145. ,  89. ,  95.5],
       [ 36. ,   1. ,   2. ,   2. ,  99. ,  59. ,  95.5],
       [ 33. ,   2. ,   1. ,   1. , 118. ,  70. , 111.7],
       [ 38. ,   1. ,   2. ,   2. , 117. ,  74. , 132.1],
       [ 34. ,   2. ,   1. ,   1. , 122. ,  74. ,  97.1],
       [ 38. ,   2. ,   1. ,   1. , 102. ,  58. , 116.5],
       [ 37. ,   1. ,   2. ,   2. ,  99. ,  68. , 111.2],
       [ 34. ,   2. ,   1. ,   1. , 111. ,  58. ,  97.7],
       [ 34. ,   2. ,   1. ,   1. , 108. ,  61. , 111.2],
       [ 44. ,   1. ,   2. ,   1. , 138. ,  84. , 115.5],
       [ 70. ,   1. ,   1. ,   2. , 104. ,  63. , 102.1],
       [ 58. ,   1. ,   2. ,   1. , 136. ,  80. , 112.2],
       [ 40. ,   1. ,   3. ,   2. , 161. , 108. ,  87.9],
       [ 60. ,

In [5]:
y

array([14., 44., 29., 51., 14., 20., 11., 32.,  6., 13., 28.,  9., 10.,
       20.,  6., 16., 84., 19., 11., 13., 32., 29., 19., 20., 25., 26.,
       29., 16.,  9., 21., 13.])

In [6]:
# 상수항 추가
X_aug = sm.add_constant(X, prepend=False)

In [9]:
num_repeat = 10
num_train = 20
num_test = X.shape[0] - num_train

In [10]:
X_aug.shape

(31, 8)

In [11]:
train_idx_repeat = np.zeros([num_repeat, num_train], dtype=np.int)
test_idx_repeat = np.zeros([num_repeat, num_test], dtype=np.int)
print(train_idx_repeat)

[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]]


In [12]:
test_idx_repeat

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [13]:
from sklearn.model_selection import train_test_split
# generate train/test idx
for rep in range(num_repeat):
    idx = np.arange(X.shape[0])
    train_idx_repeat[rep, :], test_idx_repeat[rep, :] = train_test_split(idx, train_size = num_train, test_size=num_test)
    print(rep)
    
    print(train_idx_repeat[rep, :])
    print(test_idx_repeat[rep, :])
    

0
[11  3 27 23 17 30 14 12 13  9 20 26  2 18  0 21  4 22 29  7]
[15 24 28 19  5 25  1  6 16 10  8]
1
[ 8 20 25 12 23 30 28  7  3 11  0 17  2 13  6 16 19 10 15 14]
[18 22 26 29 21  4  1 24  5  9 27]
2
[26  3  1 25 16 27  7 28 11  5 24 21  6 23 15 12 30 20  2 19]
[29 14 22  0 10 18  4 13 17  9  8]
3
[25  2 12  0 15 23 18 19 11 30 20 29  7 27  6 13  4  5  1 24]
[22  3 16 28 21 17  9 26  8 10 14]
4
[26  9 30 24 10 16 19  5 17  8 15 27 20 28 21  4  6  7 22 29]
[18 12  1 11 23 13  0 14  2 25  3]
5
[20 27  6 17 15 26  8 10  5 23  4  2 19 14 25 11 16 18 24 30]
[22 28  9  1 29 13 12  3 21  0  7]
6
[17  1 22  8 30  5  3 13 25  6  4 27 16  9 19  7  2 26 12 18]
[15 11 21 14  0 23 20 29 10 24 28]
7
[25 23 18 12 29  9 22 17 15 11 20 13  5 27 14  8 26  2  6 30]
[ 7  3 21 19  0 16 28  4  1 10 24]
8
[ 9 20  0 23 11 22  1 25 24  5 13 19 16 12 21 10 15  7  6 30]
[18 27  8 17  2 29 26  4 28 14  3]
9
[22 16 20  0 29 17  7 10 26 18 14  2 12  6  1 28 23 13 15 11]
[ 5 24 19  9  4 21  8  3 25 27 30]


In [14]:
print(train_idx_repeat)

[[11  3 27 23 17 30 14 12 13  9 20 26  2 18  0 21  4 22 29  7]
 [ 8 20 25 12 23 30 28  7  3 11  0 17  2 13  6 16 19 10 15 14]
 [26  3  1 25 16 27  7 28 11  5 24 21  6 23 15 12 30 20  2 19]
 [25  2 12  0 15 23 18 19 11 30 20 29  7 27  6 13  4  5  1 24]
 [26  9 30 24 10 16 19  5 17  8 15 27 20 28 21  4  6  7 22 29]
 [20 27  6 17 15 26  8 10  5 23  4  2 19 14 25 11 16 18 24 30]
 [17  1 22  8 30  5  3 13 25  6  4 27 16  9 19  7  2 26 12 18]
 [25 23 18 12 29  9 22 17 15 11 20 13  5 27 14  8 26  2  6 30]
 [ 9 20  0 23 11 22  1 25 24  5 13 19 16 12 21 10 15  7  6 30]
 [22 16 20  0 29 17  7 10 26 18 14  2 12  6  1 28 23 13 15 11]]


In [15]:
# Repeat evaluation 
from sklearn.metrics import mean_squared_error
mse_train_repeat = np.zeros(num_repeat)
mse_test_repeat = np.zeros(num_repeat)

In [16]:
print(mse_train_repeat)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [17]:
print(mse_test_repeat)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [18]:
for rep in range(num_repeat):
    train_idx, test_idx = train_idx_repeat[rep, :], test_idx_repeat[rep, :]
    
    train_X_aug, test_X_aug = X_aug[train_idx,:], X_aug[test_idx,:]
    train_y, test_y = y[train_idx],y[test_idx]
    
    reg = sm.OLS(train_y,train_X_aug).fit()
    
    train_y_pred = reg.predict(train_X_aug)
    mse_train_repeat[rep] = mean_squared_error(train_y, train_y_pred)
    
    test_y_pred = reg.predict(test_X_aug)
    mse_test_repeat[rep] = mean_squared_error(test_y, test_y_pred)

[ 28.21455342  28.62668324 120.17372973  10.57058079  93.0222418
  74.49885792  84.28594337  14.88825881  82.50889166 105.32289339]
[322.98655913 668.14050092  72.76087354 542.42354068 272.55621609
 250.85681622 637.72783772 381.90018117 502.81226916 130.00965862]


In [20]:
print(mse_train_repeat)

[ 28.21455342  28.62668324 120.17372973  10.57058079  93.0222418
  74.49885792  84.28594337  14.88825881  82.50889166 105.32289339]


In [19]:
print(mse_test_repeat)

[322.98655913 668.14050092  72.76087354 542.42354068 272.55621609
 250.85681622 637.72783772 381.90018117 502.81226916 130.00965862]


In [21]:
from sklearn.model_selection import KFold

In [28]:
kf = KFold(10, shuffle=True)

In [33]:
mse_train_repeat = []
mse_test_repeat = []
for train_idx, test_idx in kf.split(X_aug):
    train_X_aug, test_X_aug = X_aug[train_idx,:], X_aug[test_idx,:]
    train_y, test_y = y[train_idx],y[test_idx]
    
    reg = sm.OLS(train_y,train_X_aug).fit()
    
    train_y_pred = reg.predict(train_X_aug)
    mse_train_repeat.append(mean_squared_error(train_y, train_y_pred))
    
    test_y_pred = reg.predict(test_X_aug)
    mse_test_repeat.append(mean_squared_error(test_y, test_y_pred))

In [35]:
np.c_[mse_train_repeat, mse_test_repeat]

array([[  95.7543975 ,  118.52105389],
       [  95.11862436,  247.52156245],
       [  94.50760573,  139.70203926],
       [ 103.09889387,   37.16893319],
       [  28.14279718, 1124.10414595],
       [ 103.66956023,   40.58598362],
       [  91.04764203,  256.79139838],
       [  97.74850191,  170.43419086],
       [ 101.40416003,   57.82422211],
       [ 101.30356421,  158.05502843]])

In [31]:
mse_test_repeat

array([322.98655913, 668.14050092,  72.76087354, 542.42354068,
       272.55621609, 250.85681622, 637.72783772, 381.90018117,
       502.81226916,  90.92386683])